# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Future Computing with Rogues Gallery VIP
email: jyoung9@gatech.edu
description: >- # this means to ignore newlines until "baseurl:"
  The aim of the Rogues Gallery Vertically Integrated Project (VIP) class, is to train students to use
  novel computing architectures, tools, algorithms, and applications. Specifically, it focuses on
  candidate technologies for post-Moore computing and researching new ways to use these
  technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: GT_CRNCH_RG
github_username:  gt-crnch-rg/fc-with-rg-vip

# Build settings
# theme: jekyll-theme-basically-basic
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

# Plugins
plugins: # previously gems
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections
collections:
  resources:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # development
  - scope:
      path: "resources/development"
      type: posts
    values:
      layout: post
      read_time: true
  # linux
  - scope:
      path: "resources/linux"
      type: posts
    values:
      layout: post
      read_time: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
